### ISSUE TITLE
Would love to have a shortcut key to toggle menu

### ISSUE THREAD

**Issue by saurabhdaware** [Raathigesh/waypoint#16]
I think having a shortcut key will improve the experience for the user :D 

Also, if you agree, let me know if I can contribute and a keybind that you'll prefer.

**Comment by Raathigesh** [comment]
I agree. Right now if you open the VSCode command panel, there is a command called "Toggle Waypoint panel" which can be manually key-mapped to any shortcut. I have it mapped to `command + shift + space` but having this pre configured would be really nice.

I'm not sure what's the right key combination though. Feel free to pick a combo and we can change it later if we want to.
