### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by sahandevs** [Raathigesh/waypoint#2]
I installed the extension and played with it for a while. I absolutely loved it. I know this is in the very early stage so i will put all the things here:

### __Suggestion__
- __clicking on a keyword will move the stage to the target window when it's offstage__

![image](https://user-images.githubusercontent.com/1113944/73658313-5b18f100-46a9-11ea-8edc-cb2ac46b6ca2.png)

(`skeleton` window is opened and offstage)
after clicking on skeleton
![image](https://user-images.githubusercontent.com/1113944/73658278-4e949880-46a9-11ea-9c08-8db062248e70.png)

it would be great to update the history states so we can use the back button on the mouse to go to the previous position.

- __opened windows__
a window that shows list of opened windows and when clicked on one it will show the window on the stage.

- __Indicate related window when hovering over the source__
![image](https://user-images.githubusercontent.com/1113944/73657975-9f57c180-46a8-11ea-86cc-671c8e511708.png)
(mouse is over `theme` and the window left is indicated with black border)

- __Support for regions__
currently we can add a file or symbol to stage.It would be amazing if could use regions too.
some use cases and examples:
react hooks:
![image](https://user-images.githubusercontent.com/1113944/73657673-01fc8d80-46a8-11ea-9c4f-a0758fc99426.png)
a class that can have two regions:
region values:
![image](https://user-images.githubusercontent.com/1113944/73657819-53a51800-46a8-11ea-954b-674e31b7380b.png)
region elements:
![image](https://user-images.githubusercontent.com/1113944/73657871-6881ab80-46a8-11ea-9ae3-6031d83935b5.png)

##### __Bugs__

- Sometimes texts get blurry
![image](https://user-images.githubusercontent.com/1113944/73657260-286df900-46a7-11ea-90e5-7a11673ad818.png)
(notice right window is blury but left is not)

**Comment by Raathigesh** [comment]
Thanks for your feedback. Appreciate it.

**Comment by Raathigesh** [comment]
Hey 👋,
 
Shipped a new outline view which popups up when you press `.` will allow you to navigate between symbols on the stage easily. 

Also, the symbols on stage will persist between refreshes or restarts now.
