### ISSUE TITLE
How to exclude folders from index?

### ISSUE THREAD

**Issue by JohanHeyvaert** [Raathigesh/waypoint#21]
Hi,
The index includes result from the build (/dist folder). How can we exclude this folder? The configuration only seems to allow adding folders.
Thanks for your feedback.
Johan

**Comment by Raathigesh** [comment]
Hi 👋 ,

Right now you can't but I understand this is a fundamental configuration that should be available. Will prioritize it.

**Comment by CatsMiaow** [comment]
I wish I could exclude the extension too.
e.g. exclude of js files in typescript project

**Comment by Raathigesh** [comment]
This is now available. please try the new release - https://github.com/Raathigesh/waypoint/releases/tag/0.39.0
