### ISSUE TITLE
Not able to open other bubble windows by clicking on symbols

### ISSUE THREAD

**Issue by cksachdev** [Raathigesh/waypoint#5]
I have indexed a react project in JS Bubbles. I am manually able to open the component files. I could see small markers in the right column 
![image](https://user-images.githubusercontent.com/37770/78128356-61baaf00-7433-11ea-9738-4639028c3468.png)

But nothing happens when I click on it, click gets captured by Scroll bar. Doing a Cmd + click on the symbol also doesn't do anything and there is no error. 
@Raathigesh Any suggestion or workarounds to make it work?

**Comment by Raathigesh** [comment]
Hi 👋,

The markers suppose to in the bubble (on top of the text) and not on the scrollbar. 

Please do let me know if those are not available.

**Comment by cksachdev** [comment]
@Raathigesh Yes, there are hyper links, but nothing happens when I click on those. Let me know if I can share logs in any way from vscode.

**Comment by Raathigesh** [comment]
Hi, This project's direction has changed a bit. Please re-try if the extension is still relevant for you.
