### ISSUE TITLE
Crashing on large projects

### ISSUE THREAD

**Issue by mdchristians** [Raathigesh/waypoint#6]
I've got a rather large project that seems to crash the extension as it exceeds the memory limit. It's currently failing around the 3k-6k file mark, which unfortunately is about 15% of the way through indexing.

**Comment by Raathigesh** [comment]
Hi @mdchristians,

thank you for showing interesting in the project. After exploring few different ideas, the direction of the project has changed from code bubbles to a faster symbol search in VSCode. We still have plans to incorporate a code bubble like approach but starting small and planning to expand the feature as we go on.

The indexer now uses a multi process mechanism to index files so it should handle large projects fairly well. If you are still interested in what the project is doing, please do give it a try and let us know :)

**Comment by mdchristians** [comment]
@Raathigesh Right on!  I'll give it a go and let y'all know.

**Comment by Raathigesh** [comment]
Closing this for now. Please reopen if we need to look into it.
