### ISSUE TITLE
Unable to get any files or symbols to be picked up

### ISSUE THREAD

**Issue by Gozala** [Raathigesh/waypoint#9]
I have no lack getting JSBubble to pick up any files. I've attempted to:

1. Add relative paths to the config
2. Add absolute paths to the config
3. Clicking `Start Indexing` 

But no errors are reported but also no files appear to be picked up:

<img width="421" alt="image" src="https://user-images.githubusercontent.com/21236/83018473-3a6b0300-9fda-11ea-9c91-1dbf989be31e.png">

I have also tried to add file via (Add file to stage) command but that also just creates empty bubble

<img width="414" alt="image" src="https://user-images.githubusercontent.com/21236/83018446-2cb57d80-9fda-11ea-88e8-66db03d6acfe.png">

Any help trying to figure this out would be great!

### VSCode Metadata
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (1 wk ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by Raathigesh** [comment]
Hi @Gozala ,

thank you for showing interesting in the project. After exploring few different ideas, the direction of the project has changed from code bubbles to a faster symbol search in VSCode. We still have plans to incorporate a code bubble like approach but starting small and planning to expand the feature as we go on.

If you are still keen, could you please give it a try with our new build of waypoint.
